In [1]:
# ============================================================
# NOTEBOOK 07 — CUSTOMER RESPONSE PREDICTION
# ============================================================

import pandas as pd
import numpy as np

from pathlib import Path

project_root = Path.cwd().parent

data_path = (
    project_root
    / "data"
    / "processed"
    / "behavioral_data.csv"
)

data = pd.read_csv(data_path)

print("=" * 65)
print("CUSTOMER RESPONSE PREDICTION")
print("=" * 65)

print("\nDataset shape:", data.shape)

print("\nColumns:")
print(data.columns.tolist())

print("\nTarget distribution:")
print(data["deposit"].value_counts())

print("\nTarget percentage:")
print(
    data["deposit"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

=================================================================
CUSTOMER RESPONSE PREDICTION
=================================================================

Dataset shape: (11162, 17)

Columns:
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'deposit']

Target distribution:
deposit
no     5873
yes    5289
Name: count, dtype: int64

Target percentage:
deposit
no     52.62
yes    47.38
Name: proportion, dtype: float64

In [1]:
# ============================================================
# TARGET VARIABLE
# ============================================================

data["target"] = (
    data["deposit"]
    .str.lower()
    .eq("yes")
    .astype(int)
)

print("Target encoding:")
print("No  = 0")
print("Yes = 1")

print("\nDistribution:")
print(data["target"].value_counts())

print("\nPercentage:")
print(
    data["target"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

NameError: name 'data' is not defined

In [3]:
# ============================================================
# NUDGEIQ - NOTEBOOK 07
# INITIALIZE DATA
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path

print("Starting NudgeIQ...")

# Find project root
project_root = Path.cwd().parent

print("Current directory:", Path.cwd())
print("Project root:", project_root)

# Load the behavioral intelligence dataset
data_path = (
    project_root
    / "data"
    / "processed"
    / "behavioral_intelligence.csv"
)

print("Looking for:")
print(data_path)

# Check whether file exists
if not data_path.exists():
    raise FileNotFoundError(
        f"\nFile not found:\n{data_path}\n\n"
        "Please check that your notebook is inside the NudgeIQ/notebooks folder."
    )

# Load dataset
data = pd.read_csv(data_path)

print("\nSUCCESS!")
print("Dataset shape:", data.shape)

print("\nFirst 5 rows:")
display(data.head())

print("\nColumns:")
print(data.columns.tolist())

Starting NudgeIQ...
Current directory: d:\NudgeIQ\notebooks
Project root: d:\NudgeIQ
Looking for:
d:\NudgeIQ\data\processed\behavioral_intelligence.csv

SUCCESS!
Dataset shape: (11162, 37)

First 5 rows:

,age,job,marital,education,default,balance,housing,loan,contact,day,...,Financial_Stability,Contact_Intensity,Relationship_History,Investment_Experience,Responsiveness,Investment_Readiness,Financial_Index,Engagement_Index,Investor_Profile_Index,Behavioral_Intelligence_Score
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,...,0.069866,0.719228,-0.36326,1.029603,1.930226,1.282201,0.069866,0.425828,1.282201,0.832651
1,56,admin.,married,secondary,no,45,no,no,unknown,5,...,-0.124253,0.719228,-0.36326,0.814669,3.154612,1.107073,-0.124253,0.425828,1.107073,0.652918
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,...,-0.234045,0.719228,-0.36326,-0.260003,2.929901,0.231430,-0.234045,0.425828,0.231430,0.203709
3,55,services,married,secondary,no,2476,yes,no,unknown,5,...,0.107537,0.719228,-0.36326,0.743024,0.596366,1.048697,0.107537,0.425828,1.048697,0.747817
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,...,-0.084883,0.995583,-0.36326,1.524871,0.867171,1.856072,-0.084883,0.672507,1.856072,1.137478

Columns:
['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'deposit', 'housing_num', 'loan_num', 'default_num', 'contact_num', 'education_num', 'age_z', 'balance_z', 'campaign_z', 'previous_z', 'duration_z', 'Financial_Stability', 'Contact_Intensity', 'Relationship_History', 'Investment_Experience', 'Responsiveness', 'Investment_Readiness', 'Financial_Index', 'Engagement_Index', 'Investor_Profile_Index', 'Behavioral_Intelligence_Score']

In [4]:
# ============================================================
# CHECK TARGET
# ============================================================

print("Checking deposit column...")

if "deposit" not in data.columns:
    raise KeyError(
        "The column 'deposit' does not exist in this dataset."
    )

print("\nDeposit values:")
print(data["deposit"].value_counts(dropna=False))

Checking deposit column...

Deposit values:
deposit
no     5873
yes    5289
Name: count, dtype: int64

In [5]:
# ============================================================
# CELL 2 — TARGET CHECK
# ============================================================

print("=" * 60)
print("TARGET VARIABLE CHECK")
print("=" * 60)

print("\nDeposit values:")
print(data["deposit"].value_counts(dropna=False))

print("\nDeposit percentages:")
print(
    data["deposit"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

============================================================
TARGET VARIABLE CHECK
============================================================

Deposit values:
deposit
no     5873
yes    5289
Name: count, dtype: int64

Deposit percentages:
deposit
no     52.62
yes    47.38
Name: proportion, dtype: float64

In [6]:
# ============================================================
# CELL 3 — CREATE BINARY TARGET
# ============================================================

data["target"] = (
    data["deposit"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("yes")
    .astype(int)
)

print("Target created successfully.")

print("\nTarget counts:")
print(data["target"].value_counts())

print("\nTarget percentages:")
print(
    data["target"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Target created successfully.

Target counts:
target
0    5873
1    5289
Name: count, dtype: int64

Target percentages:
target
0    52.62
1    47.38
Name: proportion, dtype: float64

In [7]:
# ============================================================
# CELL 4 — DEFINE BASELINE PREDICTORS
# ============================================================

feature_columns = [
    # Customer profile
    "age",
    "job",
    "marital",
    "education",

    # Financial position
    "default",
    "balance",
    "housing",
    "loan",

    # Contact / campaign information
    "contact",
    "campaign",
    "pdays",
    "previous",
    "poutcome"
]

X = data[feature_columns].copy()
y = data["target"].copy()

print("=" * 60)
print("BASELINE MODEL DATA")
print("=" * 60)

print("\nX shape:", X.shape)
print("y shape:", y.shape)

print("\nPredictor columns:")
for column in feature_columns:
    print(" -", column)

print("\nMissing values:")
print(X.isnull().sum().sum())

print("\nTarget distribution:")
print(y.value_counts())

============================================================
BASELINE MODEL DATA
============================================================

X shape: (11162, 13)
y shape: (11162,)

Predictor columns:
 - age
 - job
 - marital
 - education
 - default
 - balance
 - housing
 - loan
 - contact
 - campaign
 - pdays
 - previous
 - poutcome

Missing values:
0

Target distribution:
target
0    5873
1    5289
Name: count, dtype: int64

In [8]:
# ============================================================
# CELL 5 — TRAIN / TEST SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("=" * 60)
print("TRAIN / TEST SPLIT")
print("=" * 60)

print("\nTraining rows:", len(X_train))
print("Testing rows:", len(X_test))

print("\nTraining target:")
print(
    y_train.value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nTesting target:")
print(
    y_test.value_counts(normalize=True)
    .mul(100)
    .round(2)
)

============================================================
TRAIN / TEST SPLIT
============================================================

Training rows: 8929
Testing rows: 2233

Training target:
target
0    52.62
1    47.38
Name: proportion, dtype: float64

Testing target:
target
0    52.62
1    47.38
Name: proportion, dtype: float64

In [9]:
# ============================================================
# CELL 6 — PREPROCESSING
# ============================================================

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Categorical variables
categorical_features = [
    "job",
    "marital",
    "education",
    "default",
    "housing",
    "loan",
    "contact",
    "poutcome"
]

# Numerical variables
numerical_features = [
    "age",
    "balance",
    "campaign",
    "pdays",
    "previous"
]

print("=" * 60)
print("PREPROCESSING SETUP")
print("=" * 60)

print("\nCategorical features:")
for col in categorical_features:
    print(" -", col)

print("\nNumerical features:")
for col in numerical_features:
    print(" -", col)

# Create preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        ),
        (
            "numerical",
            StandardScaler(),
            numerical_features
        )
    ]
)

print("\nPreprocessor created successfully.")

============================================================
PREPROCESSING SETUP
============================================================

Categorical features:
 - job
 - marital
 - education
 - default
 - housing
 - loan
 - contact
 - poutcome

Numerical features:
 - age
 - balance
 - campaign
 - pdays
 - previous

Preprocessor created successfully.

In [10]:
# ============================================================
# CELL 7 — LOGISTIC REGRESSION
# ============================================================

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            LogisticRegression(
                max_iter=2000,
                random_state=42
            )
        )
    ]
)

# Train
logistic_model.fit(
    X_train,
    y_train
)

print("=" * 60)
print("LOGISTIC REGRESSION")
print("=" * 60)

print("Model trained successfully.")

============================================================
LOGISTIC REGRESSION
============================================================
Model trained successfully.

In [11]:
# ============================================================
# CELL 8 — LOGISTIC REGRESSION EVALUATION
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Predictions
logistic_prediction = logistic_model.predict(X_test)

# Probability of positive class
logistic_probability = (
    logistic_model.predict_proba(X_test)[:, 1]
)

# Metrics
logistic_accuracy = accuracy_score(
    y_test,
    logistic_prediction
)

logistic_precision = precision_score(
    y_test,
    logistic_prediction
)

logistic_recall = recall_score(
    y_test,
    logistic_prediction
)

logistic_f1 = f1_score(
    y_test,
    logistic_prediction
)

logistic_auc = roc_auc_score(
    y_test,
    logistic_probability
)

print("=" * 60)
print("LOGISTIC REGRESSION — MODEL EVALUATION")
print("=" * 60)

print(f"\nAccuracy : {logistic_accuracy:.4f}")
print(f"Precision: {logistic_precision:.4f}")
print(f"Recall   : {logistic_recall:.4f}")
print(f"F1 Score : {logistic_f1:.4f}")
print(f"ROC-AUC  : {logistic_auc:.4f}")

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        logistic_prediction
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        logistic_prediction
    )
)

============================================================
LOGISTIC REGRESSION — MODEL EVALUATION
============================================================

Accuracy : 0.6726
Precision: 0.6811
Recall   : 0.5813
F1 Score : 0.6272
ROC-AUC  : 0.7293

Confusion Matrix:
[[887 288]
 [443 615]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.75      0.71      1175
           1       0.68      0.58      0.63      1058

    accuracy                           0.67      2233
   macro avg       0.67      0.67      0.67      2233
weighted avg       0.67      0.67      0.67      2233

In [12]:
# ============================================================
# CELL 9 — LOAD EXISTING NUDGEIQ OUTPUT
# ============================================================

from pathlib import Path
import pandas as pd

project_root = Path.cwd().parent

nudgeiq_path = (
    project_root
    / "data"
    / "processed"
    / "final_nudgeiq_output.csv"
)

print("=" * 60)
print("LOADING EXISTING NUDGEIQ OUTPUT")
print("=" * 60)

print("\nLooking for:")
print(nudgeiq_path)

if not nudgeiq_path.exists():
    raise FileNotFoundError(
        f"\nFile not found:\n{nudgeiq_path}"
    )

nudgeiq = pd.read_csv(nudgeiq_path)

print("\nSUCCESS!")
print("Shape:", nudgeiq.shape)

print("\nColumns:")
print(nudgeiq.columns.tolist())

print("\nFirst 5 customers:")
display(nudgeiq.head())

============================================================
LOADING EXISTING NUDGEIQ OUTPUT
============================================================

Looking for:
d:\NudgeIQ\data\processed\final_nudgeiq_output.csv

SUCCESS!
Shape: (11162, 14)

Columns:
['age', 'job', 'marital', 'education', 'balance', 'Persona', 'Tier', 'Priority', 'Action', 'Nudge_Objective', 'Recommended_Intervention', 'Target_KPI', 'Nudge_Priority_Score', 'Nudge_Priority_Band']

First 5 customers:

,age,job,marital,education,balance,Persona,Tier,Priority,Action,Nudge_Objective,Recommended_Intervention,Target_KPI,Nudge_Priority_Score,Nudge_Priority_Band
0,59,admin.,married,secondary,2343,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,Recommend complementary gold/silver investment...,Gold vs Silver Preference Ratio,0.420542,Medium
1,56,admin.,married,secondary,45,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,Recommend complementary gold/silver investment...,Gold vs Silver Preference Ratio,0.417306,Medium
2,41,technician,married,secondary,1270,General Investor,Tier 2,Medium,Nurture with periodic offers and reviews,Maintain engagement and encourage repeat inves...,Periodic portfolio review and personalized inv...,Repeat Purchase Rate,0.407787,Medium
3,55,services,married,secondary,2476,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,Recommend complementary gold/silver investment...,Gold vs Silver Preference Ratio,0.418521,Medium
4,54,admin.,married,tertiary,184,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,Recommend complementary gold/silver investment...,Gold vs Silver Preference Ratio,0.427250,Medium

In [13]:
# ============================================================
# CELL 10 — VERIFY EXISTING NUDGEIQ PERSONAS
# ============================================================

print("=" * 60)
print("EXISTING NUDGEIQ PERSONAS")
print("=" * 60)

persona_summary = (
    nudgeiq["Persona"]
    .value_counts()
    .rename_axis("Persona")
    .reset_index(name="Customers")
)

persona_summary["Percentage"] = (
    persona_summary["Customers"]
    / len(nudgeiq)
    * 100
).round(2)

display(persona_summary)

============================================================
EXISTING NUDGEIQ PERSONAS
============================================================

                 Persona  Customers  Percentage
0      Inactive Investor       2378       21.30
1      Balanced Investor       2151       19.27
2       General Investor       1873       16.78
3    Low Engagement User       1455       13.04
4      Emerging Investor       1168       10.46
5     Potential Investor        926        8.30
6  Dormant Wealth Holder        555        4.97
7        Growth Investor        433        3.88
8       Premium Investor        223        2.00

In [14]:
# ============================================================
# CELL 11 — EXISTING RULE-BASED NUDGE ENGINE
# ============================================================

decision_summary = (
    nudgeiq[
        [
            "Persona",
            "Tier",
            "Priority",
            "Action",
            "Nudge_Objective",
            "Recommended_Intervention",
            "Target_KPI"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Tier", "Persona"]
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("EXISTING NUDGE DECISION ENGINE")
print("=" * 70)

print("\nUnique decision combinations:", len(decision_summary))

display(decision_summary)

======================================================================
EXISTING NUDGE DECISION ENGINE
======================================================================

Unique decision combinations: 15

,Persona,Tier,Priority,Action,Nudge_Objective,Recommended_Intervention,Target_KPI
0,Growth Investor,Tier 1,High,Upsell high-growth investment products,Increase investment depth,Recommend suitable higher-value or growth-orie...,Average Investment per User
1,Growth Investor,Tier 1,High,Upsell high-growth investment products; increa...,Increase investment depth and strengthen engag...,Provide a growth-product recommendation with a...,Average Investment per User
2,Growth Investor,Tier 1,High,Upsell growth products; review profile data qu...,Increase investment depth and improve profile ...,Review customer profile data and provide a sui...,Average Investment per User
3,Premium Investor,Tier 1,High,Assign dedicated RM; offer premium/exclusive p...,Maximize high-value customer relationship,Dedicated relationship-manager outreach with p...,Average Wallet Holding
4,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,Recommend complementary gold/silver investment...,Gold vs Silver Preference Ratio
5,General Investor,Tier 2,Medium,Nurture with periodic offers and reviews,Maintain engagement and encourage repeat inves...,Periodic portfolio review and personalized inv...,Repeat Purchase Rate
6,General Investor,Tier 2,Medium,Nurture with periodic offers; monitor profile ...,Maintain engagement and monitor behavioral change,Periodic review with behavioral trend monitori...,Retention Rate
7,Emerging Investor,Tier 3,Medium,Educational content and onboarding nudges,Build investment confidence and encourage conv...,Provide educational investment content followe...,KYC Completion Rate
8,Potential Investor,Tier 3,Medium,Targeted conversion campaign,Convert investment interest into active invest...,Targeted conversion message with a relevant lo...,Current Month Active Investors
9,Potential Investor,Tier 3,Medium,Targeted conversion campaign; re-engage on low...,Convert interest while addressing declining ac...,Re-engagement message followed by a targeted i...,Current Month Active Investors
10,Dormant Wealth Holder,Tier 4,High,Reactivation campaign - high value,Reactivate high-value inactive customers,Personalized reactivation campaign focused on ...,Dormant User Reactivation Rate
11,Dormant Wealth Holder,Tier 4,High,Reactivation campaign - high value; senior RM ...,Reactivate high-value customers through person...,Senior relationship-manager outreach with a pe...,Dormant User Reactivation Rate
12,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,Standard reactivation campaign with a relevant...,Dormant User Reactivation Rate
13,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value; priority...,Prioritize reactivation of valuable inactive c...,Priority follow-up with personalized reactivat...,Dormant User Reactivation Rate
14,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,Low-cost digital reactivation message or depri...,Dormant User Reactivation Rate

In [15]:
# ============================================================
# CELL 12 — GOLD NUDGE DECISION MATRIX
# ============================================================

gold_rules = {

    "Premium Investor": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Introduce gold as a strategic portfolio allocation",
        "Gold_Nudge_Type": "Personalized Wealth Recommendation",
        "Gold_Channel": "Relationship Manager",
        "Gold_Message": "Explore how a strategic allocation to gold could complement your existing investment portfolio.",
        "Gold_KPI": "Gold Investment Conversion"
    },

    "Growth Investor": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Position gold as a portfolio diversification opportunity",
        "Gold_Nudge_Type": "Portfolio Diversification Recommendation",
        "Gold_Channel": "RM + Digital",
        "Gold_Message": "Looking to diversify your growth-focused portfolio? Explore how gold could complement your existing investments.",
        "Gold_KPI": "Gold Investment Conversion"
    },

    "Balanced Investor": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Increase portfolio diversification through gold",
        "Gold_Nudge_Type": "Diversification Recommendation",
        "Gold_Channel": "Digital",
        "Gold_Message": "Consider adding gold to your portfolio as another layer of diversification.",
        "Gold_KPI": "Gold Investment Conversion"
    },

    "General Investor": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Introduce gold as an additional investment option",
        "Gold_Nudge_Type": "Personalized Investment Offer",
        "Gold_Channel": "Digital",
        "Gold_Message": "Looking to diversify your investments? Explore gold as another investment option.",
        "Gold_KPI": "Gold Nudge Engagement Rate"
    },

    "Potential Investor": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Convert investment interest into a first gold investment",
        "Gold_Nudge_Type": "Conversion Nudge",
        "Gold_Channel": "Digital",
        "Gold_Message": "Ready to take your next investment step? Explore gold as an option for starting your investment journey.",
        "Gold_KPI": "Gold Investment Conversion"
    },

    "Emerging Investor": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Build confidence and encourage first gold investment",
        "Gold_Nudge_Type": "Education + Conversion",
        "Gold_Channel": "Digital",
        "Gold_Message": "Curious about investing in gold? Learn more about gold investing and explore how you can get started.",
        "Gold_KPI": "Gold Education-to-Conversion Rate"
    },

    "Dormant Wealth Holder": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Reactivate high-value customers through a gold investment conversation",
        "Gold_Nudge_Type": "Reactivation + Personalized Offer",
        "Gold_Channel": "Relationship Manager",
        "Gold_Message": "We'd like to help you review your investment options. Explore whether gold could complement your current financial strategy.",
        "Gold_KPI": "Gold Reactivation Conversion"
    },

    "Inactive Investor": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Re-engage inactive customers through a relevant gold investment opportunity",
        "Gold_Nudge_Type": "Reactivation Nudge",
        "Gold_Channel": "Digital + RM",
        "Gold_Message": "It's a good time to review your investment options. Explore gold as one way to diversify your investments.",
        "Gold_KPI": "Gold Re-engagement Rate"
    },

    "Low Engagement User": {
        "Gold_Nudge": "YES",
        "Gold_Objective": "Re-engage efficiently with a simple gold investment proposition",
        "Gold_Nudge_Type": "Low-Friction Digital Nudge",
        "Gold_Channel": "Digital",
        "Gold_Message": "Interested in exploring new investment options? Discover gold in a simple, easy-to-understand format.",
        "Gold_KPI": "Gold Nudge Engagement Rate"
    }
}

print("=" * 70)
print("GOLD NUDGE DECISION MATRIX")
print("=" * 70)

gold_matrix = (
    pd.DataFrame.from_dict(
        gold_rules,
        orient="index"
    )
    .reset_index()
    .rename(columns={"index": "Persona"})
)

display(gold_matrix)

======================================================================
GOLD NUDGE DECISION MATRIX
======================================================================

,Persona,Gold_Nudge,Gold_Objective,Gold_Nudge_Type,Gold_Channel,Gold_Message,Gold_KPI
0,Premium Investor,YES,Introduce gold as a strategic portfolio alloca...,Personalized Wealth Recommendation,Relationship Manager,Explore how a strategic allocation to gold cou...,Gold Investment Conversion
1,Growth Investor,YES,Position gold as a portfolio diversification o...,Portfolio Diversification Recommendation,RM + Digital,Looking to diversify your growth-focused portf...,Gold Investment Conversion
2,Balanced Investor,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion
3,General Investor,YES,Introduce gold as an additional investment option,Personalized Investment Offer,Digital,Looking to diversify your investments? Explore...,Gold Nudge Engagement Rate
4,Potential Investor,YES,Convert investment interest into a first gold ...,Conversion Nudge,Digital,Ready to take your next investment step? Explo...,Gold Investment Conversion
5,Emerging Investor,YES,Build confidence and encourage first gold inve...,Education + Conversion,Digital,Curious about investing in gold? Learn more ab...,Gold Education-to-Conversion Rate
6,Dormant Wealth Holder,YES,Reactivate high-value customers through a gold...,Reactivation + Personalized Offer,Relationship Manager,We'd like to help you review your investment o...,Gold Reactivation Conversion
7,Inactive Investor,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate
8,Low Engagement User,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate

In [16]:
# ============================================================
# CELL 13 — APPLY GOLD NUDGE RULES TO CUSTOMERS
# ============================================================

# Merge the Gold Decision Matrix with the existing NudgeIQ output
nudgeiq_gold = nudgeiq.merge(
    gold_matrix,
    on="Persona",
    how="left"
)

print("=" * 70)
print("GOLD NUDGE ENGINE — CUSTOMER OUTPUT")
print("=" * 70)

print("\nTotal customers:", len(nudgeiq_gold))

print(
    "Expected customers:",
    len(nudgeiq)
)

print("\nMissing Gold Nudge assignments:")
print(
    nudgeiq_gold["Gold_Nudge"]
    .isna()
    .sum()
)

print("\nGold Nudge distribution:")
print(
    nudgeiq_gold["Gold_Nudge"]
    .value_counts(dropna=False)
)

print("\nGold Channel distribution:")
print(
    nudgeiq_gold["Gold_Channel"]
    .value_counts(dropna=False)
)

print("\nSample customer-level output:")

display(
    nudgeiq_gold[
        [
            "age",
            "balance",
            "Persona",
            "Tier",
            "Priority",
            "Nudge_Priority_Score",
            "Gold_Nudge",
            "Gold_Objective",
            "Gold_Nudge_Type",
            "Gold_Channel",
            "Gold_KPI"
        ]
    ].head(10)
)

======================================================================
GOLD NUDGE ENGINE — CUSTOMER OUTPUT
======================================================================

Total customers: 11162
Expected customers: 11162

Missing Gold Nudge assignments:
0

Gold Nudge distribution:
Gold_Nudge
YES    11162
Name: count, dtype: int64

Gold Channel distribution:
Gold_Channel
Digital                 7573
Digital + RM            2378
Relationship Manager     778
RM + Digital             433
Name: count, dtype: int64

Sample customer-level output:

,age,balance,Persona,Tier,Priority,Nudge_Priority_Score,Gold_Nudge,Gold_Objective,Gold_Nudge_Type,Gold_Channel,Gold_KPI
0,59,2343,Balanced Investor,Tier 2,Medium,0.420542,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Gold Investment Conversion
1,56,45,Balanced Investor,Tier 2,Medium,0.417306,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Gold Investment Conversion
2,41,1270,General Investor,Tier 2,Medium,0.407787,YES,Introduce gold as an additional investment option,Personalized Investment Offer,Digital,Gold Nudge Engagement Rate
3,55,2476,Balanced Investor,Tier 2,Medium,0.418521,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Gold Investment Conversion
4,54,184,Balanced Investor,Tier 2,Medium,0.427250,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Gold Investment Conversion
5,42,0,Potential Investor,Tier 3,Medium,0.336961,YES,Convert investment interest into a first gold ...,Conversion Nudge,Digital,Gold Investment Conversion
6,56,830,Potential Investor,Tier 3,Medium,0.342961,YES,Convert investment interest into a first gold ...,Conversion Nudge,Digital,Gold Investment Conversion
7,60,545,Balanced Investor,Tier 2,Medium,0.417180,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Gold Investment Conversion
8,37,1,Emerging Investor,Tier 3,Medium,0.327694,YES,Build confidence and encourage first gold inve...,Education + Conversion,Digital,Gold Education-to-Conversion Rate
9,28,5090,Growth Investor,Tier 1,High,0.571464,YES,Position gold as a portfolio diversification o...,Portfolio Diversification Recommendation,RM + Digital,Gold Investment Conversion

In [17]:
# ============================================================
# CELL 14 — GOLD NUDGE PRIORITY
# ============================================================

def assign_gold_priority(row):

    priority = str(row["Priority"]).strip().lower()
    persona = str(row["Persona"]).strip()

    # High-priority customers
    if priority == "high":
        return "HIGH"

    # Medium-priority customers
    elif priority == "medium":
        return "MEDIUM"

    # Low-priority customers
    elif priority == "low":
        return "LOW"

    # Safety fallback
    else:
        return "LOW"


nudgeiq_gold["Gold_Nudge_Priority"] = (
    nudgeiq_gold.apply(
        assign_gold_priority,
        axis=1
    )
)

print("=" * 70)
print("GOLD NUDGE PRIORITY")
print("=" * 70)

print("\nGold Nudge Priority distribution:")
print(
    nudgeiq_gold["Gold_Nudge_Priority"]
    .value_counts()
)

print("\nGold Nudge Priority percentage:")
print(
    nudgeiq_gold["Gold_Nudge_Priority"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

======================================================================
GOLD NUDGE PRIORITY
======================================================================

Gold Nudge Priority distribution:
Gold_Nudge_Priority
MEDIUM    8496
LOW       1455
HIGH      1211
Name: count, dtype: int64

Gold Nudge Priority percentage:
Gold_Nudge_Priority
MEDIUM    76.12
LOW       13.04
HIGH      10.85
Name: proportion, dtype: float64

In [18]:
# ============================================================
# CELL 15 — GOLD NUDGE ACTION
# ============================================================

def assign_gold_action(row):

    persona = row["Persona"]
    priority = row["Gold_Nudge_Priority"]

    # ========================================================
    # HIGH PRIORITY
    # ========================================================

    if priority == "HIGH":

        if persona == "Premium Investor":
            return "Immediate RM outreach for strategic gold allocation"

        elif persona == "Growth Investor":
            return "High-priority gold diversification recommendation"

        elif persona == "Dormant Wealth Holder":
            return "RM reactivation followed by personalized gold proposition"

        elif persona == "Inactive Investor":
            return "Priority reactivation followed by gold recommendation"

        else:
            return "High-priority personalized gold investment nudge"

    # ========================================================
    # MEDIUM PRIORITY
    # ========================================================

    elif priority == "MEDIUM":

        if persona == "Emerging Investor":
            return "Gold education followed by first-investment nudge"

        elif persona == "Potential Investor":
            return "Gold conversion-focused digital nudge"

        elif persona == "Balanced Investor":
            return "Digital gold diversification recommendation"

        elif persona == "General Investor":
            return "Personalized digital gold investment offer"

        elif persona == "Inactive Investor":
            return "Reactivation message followed by gold recommendation"

        elif persona == "Dormant Wealth Holder":
            return "Personalized gold investment conversation"

        else:
            return "Personalized digital gold nudge"

    # ========================================================
    # LOW PRIORITY
    # ========================================================

    else:

        if persona == "Low Engagement User":
            return "Low-cost digital gold awareness nudge"

        elif persona == "Inactive Investor":
            return "Low-cost reactivation and gold awareness"

        else:
            return "Low-cost gold education and awareness nudge"


# Apply the action
nudgeiq_gold["Gold_Nudge_Action"] = (
    nudgeiq_gold.apply(
        assign_gold_action,
        axis=1
    )
)


print("=" * 70)
print("GOLD NUDGE ACTION ENGINE")
print("=" * 70)

print(
    "\nUnique Gold Nudge Actions:",
    nudgeiq_gold["Gold_Nudge_Action"].nunique()
)

display(
    nudgeiq_gold[
        [
            "Persona",
            "Priority",
            "Gold_Nudge_Priority",
            "Gold_Nudge_Action"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Gold_Nudge_Priority", "Persona"]
    )
    .reset_index(drop=True)
)

======================================================================
GOLD NUDGE ACTION ENGINE
======================================================================

Unique Gold Nudge Actions: 9

,Persona,Priority,Gold_Nudge_Priority,Gold_Nudge_Action
0,Dormant Wealth Holder,High,HIGH,RM reactivation followed by personalized gold ...
1,Growth Investor,High,HIGH,High-priority gold diversification recommendation
2,Premium Investor,High,HIGH,Immediate RM outreach for strategic gold alloc...
3,Low Engagement User,Low,LOW,Low-cost digital gold awareness nudge
4,Balanced Investor,Medium,MEDIUM,Digital gold diversification recommendation
5,Emerging Investor,Medium,MEDIUM,Gold education followed by first-investment nudge
6,General Investor,Medium,MEDIUM,Personalized digital gold investment offer
7,Inactive Investor,Medium,MEDIUM,Reactivation message followed by gold recommen...
8,Potential Investor,Medium,MEDIUM,Gold conversion-focused digital nudge

In [19]:
# ============================================================
# CELL 17 — FINAL GOLD NUDGEIQ OUTPUT
# ============================================================

final_gold_columns = [
    "age",
    "job",
    "marital",
    "education",
    "balance",

    # Existing NudgeIQ intelligence
    "Persona",
    "Tier",
    "Priority",
    "Action",
    "Nudge_Objective",
    "Recommended_Intervention",
    "Target_KPI",
    "Nudge_Priority_Score",
    "Nudge_Priority_Band",

    # Gold Nudge layer
    "Gold_Nudge",
    "Gold_Objective",
    "Gold_Nudge_Type",
    "Gold_Channel",
    "Gold_Message",
    "Gold_KPI",
    "Gold_Nudge_Priority",
    "Gold_Nudge_Action"
]

final_gold_nudgeiq = (
    nudgeiq_gold[
        final_gold_columns
    ]
    .copy()
)

print("=" * 70)
print("FINAL GOLD NUDGEIQ OUTPUT")
print("=" * 70)

print("\nShape:")
print(final_gold_nudgeiq.shape)

print("\nColumns:")
print(final_gold_nudgeiq.columns.tolist())

print("\nMissing values:")
print(
    final_gold_nudgeiq.isnull().sum()
)

print("\nSample:")
display(
    final_gold_nudgeiq.head(10)
)

======================================================================
FINAL GOLD NUDGEIQ OUTPUT
======================================================================

Shape:
(11162, 22)

Columns:
['age', 'job', 'marital', 'education', 'balance', 'Persona', 'Tier', 'Priority', 'Action', 'Nudge_Objective', 'Recommended_Intervention', 'Target_KPI', 'Nudge_Priority_Score', 'Nudge_Priority_Band', 'Gold_Nudge', 'Gold_Objective', 'Gold_Nudge_Type', 'Gold_Channel', 'Gold_Message', 'Gold_KPI', 'Gold_Nudge_Priority', 'Gold_Nudge_Action']

Missing values:
age                         0
job                         0
marital                     0
education                   0
balance                     0
Persona                     0
Tier                        0
Priority                    0
Action                      0
Nudge_Objective             0
Recommended_Intervention    0
Target_KPI                  0
Nudge_Priority_Score        0
Nudge_Priority_Band         0
Gold_Nudge                  0
Gold_Objective              0
Gold_Nudge_Type             0
Gold_Channel                0
Gold_Message                0
Gold_KPI                    0
Gold_Nudge_Priority         0
Gold_Nudge_Action           0
dtype: int64

Sample:

,age,job,marital,education,balance,Persona,Tier,Priority,Action,Nudge_Objective,...,Nudge_Priority_Score,Nudge_Priority_Band,Gold_Nudge,Gold_Objective,Gold_Nudge_Type,Gold_Channel,Gold_Message,Gold_KPI,Gold_Nudge_Priority,Gold_Nudge_Action
0,59,admin.,married,secondary,2343,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,...,0.420542,Medium,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion,MEDIUM,Digital gold diversification recommendation
1,56,admin.,married,secondary,45,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,...,0.417306,Medium,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion,MEDIUM,Digital gold diversification recommendation
2,41,technician,married,secondary,1270,General Investor,Tier 2,Medium,Nurture with periodic offers and reviews,Maintain engagement and encourage repeat inves...,...,0.407787,Medium,YES,Introduce gold as an additional investment option,Personalized Investment Offer,Digital,Looking to diversify your investments? Explore...,Gold Nudge Engagement Rate,MEDIUM,Personalized digital gold investment offer
3,55,services,married,secondary,2476,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,...,0.418521,Medium,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion,MEDIUM,Digital gold diversification recommendation
4,54,admin.,married,tertiary,184,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,...,0.427250,Medium,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion,MEDIUM,Digital gold diversification recommendation
5,42,management,single,tertiary,0,Potential Investor,Tier 3,Medium,Targeted conversion campaign,Convert investment interest into active invest...,...,0.336961,Low,YES,Convert investment interest into a first gold ...,Conversion Nudge,Digital,Ready to take your next investment step? Explo...,Gold Investment Conversion,MEDIUM,Gold conversion-focused digital nudge
6,56,management,married,tertiary,830,Potential Investor,Tier 3,Medium,Targeted conversion campaign,Convert investment interest into active invest...,...,0.342961,Low,YES,Convert investment interest into a first gold ...,Conversion Nudge,Digital,Ready to take your next investment step? Explo...,Gold Investment Conversion,MEDIUM,Gold conversion-focused digital nudge
7,60,retired,divorced,secondary,545,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,...,0.417180,Medium,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion,MEDIUM,Digital gold diversification recommendation
8,37,technician,married,secondary,1,Emerging Investor,Tier 3,Medium,Educational content and onboarding nudges,Build investment confidence and encourage conv...,...,0.327694,Low,YES,Build confidence and encourage first gold inve...,Education + Conversion,Digital,Curious about investing in gold? Learn more ab...,Gold Education-to-Conversion Rate,MEDIUM,Gold education followed by first-investment nudge
9,28,services,single,secondary,5090,Growth Investor,Tier 1,High,Upsell high-growth investment products,Increase investment depth,...,0.571464,Medium,YES,Position gold as a portfolio diversification o...,Portfolio Diversification Recommendation,RM + Digital,Looking to diversify your growth-focused portf...,Gold Investment Conversion,HIGH,High-priority gold diversification recommendation

In [20]:
# ============================================================
# CELL 18 — GOLD NUDGEIQ VALIDATION
# ============================================================

print("=" * 70)
print("GOLD NUDGEIQ VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# 1. Customer count
# ------------------------------------------------------------

print(
    "\n1. Customer count:",
    len(final_gold_nudgeiq)
)

# ------------------------------------------------------------
# 2. Persona coverage
# ------------------------------------------------------------

print(
    "\n2. Number of personas:",
    final_gold_nudgeiq["Persona"].nunique()
)

# ------------------------------------------------------------
# 3. Gold nudge coverage
# ------------------------------------------------------------

print(
    "\n3. Gold nudge coverage:"
)

print(
    final_gold_nudgeiq["Gold_Nudge"]
    .value_counts(dropna=False)
)

# ------------------------------------------------------------
# 4. Missing Gold actions
# ------------------------------------------------------------

print(
    "\n4. Missing Gold actions:",
    final_gold_nudgeiq["Gold_Nudge_Action"]
    .isna()
    .sum()
)

# ------------------------------------------------------------
# 5. Missing Gold channels
# ------------------------------------------------------------

print(
    "5. Missing Gold channels:",
    final_gold_nudgeiq["Gold_Channel"]
    .isna()
    .sum()
)

# ------------------------------------------------------------
# 6. Priority coverage
# ------------------------------------------------------------

print(
    "\n6. Gold priority coverage:"
)

print(
    final_gold_nudgeiq["Gold_Nudge_Priority"]
    .value_counts()
)

# ------------------------------------------------------------
# 7. Duplicate rows
# ------------------------------------------------------------

print(
    "\n7. Duplicate rows:",
    final_gold_nudgeiq.duplicated().sum()
)

print("\nValidation completed.")

======================================================================
GOLD NUDGEIQ VALIDATION
======================================================================

1. Customer count: 11162

2. Number of personas: 9

3. Gold nudge coverage:
Gold_Nudge
YES    11162
Name: count, dtype: int64

4. Missing Gold actions: 0
5. Missing Gold channels: 0

6. Gold priority coverage:
Gold_Nudge_Priority
MEDIUM    8496
LOW       1455
HIGH      1211
Name: count, dtype: int64

7. Duplicate rows: 13

Validation completed.

In [21]:
# ============================================================
# CELL 19 — SAVE FINAL GOLD NUDGEIQ OUTPUT
# ============================================================

output_path = (
    project_root
    / "data"
    / "processed"
    / "final_gold_nudgeiq_output.csv"
)

final_gold_nudgeiq.to_csv(
    output_path,
    index=False
)

print("=" * 70)
print("FINAL OUTPUT SAVED")
print("=" * 70)

print("\nFile:")
print(output_path)

print("\nRows:", len(final_gold_nudgeiq))
print("Columns:", len(final_gold_nudgeiq.columns))

======================================================================
FINAL OUTPUT SAVED
======================================================================

File:
d:\NudgeIQ\data\processed\final_gold_nudgeiq_output.csv

Rows: 11162
Columns: 22

In [22]:
# ============================================================
# CELL 20 — INVESTIGATE DUPLICATES
# ============================================================

print("=" * 70)
print("DUPLICATE CUSTOMER RECORD INVESTIGATION")
print("=" * 70)

duplicate_mask = final_gold_nudgeiq.duplicated(
    keep=False
)

duplicates = (
    final_gold_nudgeiq[
        duplicate_mask
    ]
    .sort_values(
        [
            "Persona",
            "balance",
            "age"
        ]
    )
)

print("\nTotal duplicate rows:", len(duplicates))

print(
    "Number of duplicate groups:",
    duplicates.drop_duplicates().shape[0]
)

print("\nDuplicate records:")

display(duplicates)

======================================================================
DUPLICATE CUSTOMER RECORD INVESTIGATION
======================================================================

Total duplicate rows: 26
Number of duplicate groups: 13

Duplicate records:

,age,job,marital,education,balance,Persona,Tier,Priority,Action,Nudge_Objective,...,Nudge_Priority_Score,Nudge_Priority_Band,Gold_Nudge,Gold_Objective,Gold_Nudge_Type,Gold_Channel,Gold_Message,Gold_KPI,Gold_Nudge_Priority,Gold_Nudge_Action
800,45,technician,single,tertiary,0,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,...,0.408178,Medium,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion,MEDIUM,Digital gold diversification recommendation
5950,45,technician,single,tertiary,0,Balanced Investor,Tier 2,Medium,Cross-sell balanced portfolio products,Increase portfolio diversification,...,0.408178,Medium,YES,Increase portfolio diversification through gold,Diversification Recommendation,Digital,Consider adding gold to your portfolio as anot...,Gold Investment Conversion,MEDIUM,Digital gold diversification recommendation
7490,43,blue-collar,married,primary,0,Emerging Investor,Tier 3,Medium,Educational content and onboarding nudges,Build investment confidence and encourage conv...,...,0.324274,Low,YES,Build confidence and encourage first gold inve...,Education + Conversion,Digital,Curious about investing in gold? Learn more ab...,Gold Education-to-Conversion Rate,MEDIUM,Gold education followed by first-investment nudge
7709,43,blue-collar,married,primary,0,Emerging Investor,Tier 3,Medium,Educational content and onboarding nudges,Build investment confidence and encourage conv...,...,0.324274,Low,YES,Build confidence and encourage first gold inve...,Education + Conversion,Digital,Curious about investing in gold? Learn more ab...,Gold Education-to-Conversion Rate,MEDIUM,Gold education followed by first-investment nudge
5545,30,technician,single,tertiary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.241687,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
10279,30,technician,single,tertiary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.241687,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
5505,32,management,single,tertiary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.242843,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
7252,32,management,single,tertiary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.242843,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
8647,34,management,married,tertiary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.243999,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
9749,34,management,married,tertiary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.243999,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
2174,49,admin.,married,secondary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.241873,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
3478,49,admin.,married,secondary,0,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.241873,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
2464,18,student,single,unknown,108,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.237963,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
2654,18,student,single,unknown,108,Inactive Investor,Tier 4,Medium,Reactivation campaign - medium value,Reactivate medium-value inactive customers,...,0.237963,Low,YES,Re-engage inactive customers through a relevan...,Reactivation Nudge,Digital + RM,It's a good time to review your investment opt...,Gold Re-engagement Rate,MEDIUM,Reactivation message followed by gold recommen...
1535,33,management,married,tertiary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.175977,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
9461,33,management,married,tertiary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.175977,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
4178,37,admin.,married,secondary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.171404,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
8896,37,admin.,married,secondary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.171404,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
534,38,technician,married,secondary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.171982,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
1599,38,technician,married,secondary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.171982,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
2647,52,technician,married,secondary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.182414,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
7792,52,technician,married,secondary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.182414,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
473,56,blue-collar,married,primary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.175500,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
10050,56,blue-collar,married,primary,0,Low Engagement User,Tier 4,Low,Low-cost reactivation or deprioritize,Re-engage efficiently while controlling acquis...,...,0.175500,Low,YES,Re-engage efficiently with a simple gold inves...,Low-Friction Digital Nudge,Digital,Interested in exploring new investment options...,Gold Nudge Engagement Rate,LOW,Low-cost digital gold awareness nudge
4338,27,services,married,secondary,0,Potential Investor,Tier 3,Medium,Targeted conversion campaign,Convert investment interest into active invest...,...,0.347549,Low,YES,Convert investment interest into a first gold ...,Conversion Nudge,Digital,Ready to take your next investment step? Explo...,Gold Investment Conversion,MEDIUM,Gold conversion-focused digital nudge
9629,27,services,married,secondary,0,Potential Investor,Tier 3,Medium,Targeted conversion campaign,Convert investment interest into active invest...,...,0.347549,Low,YES,Convert investment interest into a first gold ...,Conversion Nudge,Digital,Ready to take your next investment step? Explo...,Gold Investment Conversion,MEDIUM,Gold conversion-focused digital nudge

In [23]:
# ============================================================
# CELL 21 — CREATE CUSTOMER ID
# ============================================================

final_gold_nudgeiq.insert(
    0,
    "Customer_ID",
    [
        f"NQ{str(i).zfill(5)}"
        for i in range(
            1,
            len(final_gold_nudgeiq) + 1
        )
    ]
)

print("=" * 70)
print("CUSTOMER ID CREATED")
print("=" * 70)

print("\nCustomer count:", len(final_gold_nudgeiq))

print("\nFirst 10 IDs:")
display(
    final_gold_nudgeiq[
        [
            "Customer_ID",
            "age",
            "Persona",
            "Gold_Nudge_Priority",
            "Gold_Nudge_Action"
        ]
    ].head(10)
)

======================================================================
CUSTOMER ID CREATED
======================================================================

Customer count: 11162

First 10 IDs:

,Customer_ID,age,Persona,Gold_Nudge_Priority,Gold_Nudge_Action
0,NQ00001,59,Balanced Investor,MEDIUM,Digital gold diversification recommendation
1,NQ00002,56,Balanced Investor,MEDIUM,Digital gold diversification recommendation
2,NQ00003,41,General Investor,MEDIUM,Personalized digital gold investment offer
3,NQ00004,55,Balanced Investor,MEDIUM,Digital gold diversification recommendation
4,NQ00005,54,Balanced Investor,MEDIUM,Digital gold diversification recommendation
5,NQ00006,42,Potential Investor,MEDIUM,Gold conversion-focused digital nudge
6,NQ00007,56,Potential Investor,MEDIUM,Gold conversion-focused digital nudge
7,NQ00008,60,Balanced Investor,MEDIUM,Digital gold diversification recommendation
8,NQ00009,37,Emerging Investor,MEDIUM,Gold education followed by first-investment nudge
9,NQ00010,28,Growth Investor,HIGH,High-priority gold diversification recommendation

In [24]:
# ============================================================
# CELL 22 — GOLD OPPORTUNITY BY PERSONA
# ============================================================

gold_opportunity = (
    final_gold_nudgeiq
    .groupby("Persona")
    .agg(
        Customers=("Customer_ID", "count"),
        High_Priority=(
            "Gold_Nudge_Priority",
            lambda x: (x == "HIGH").sum()
        ),
        Medium_Priority=(
            "Gold_Nudge_Priority",
            lambda x: (x == "MEDIUM").sum()
        ),
        Low_Priority=(
            "Gold_Nudge_Priority",
            lambda x: (x == "LOW").sum()
        ),
        Avg_Nudge_Score=(
            "Nudge_Priority_Score",
            "mean"
        ),
        Avg_Balance=(
            "balance",
            "mean"
        )
    )
    .reset_index()
)

gold_opportunity["Customer_%"] = (
    gold_opportunity["Customers"]
    / len(final_gold_nudgeiq)
    * 100
).round(2)

gold_opportunity["Avg_Nudge_Score"] = (
    gold_opportunity["Avg_Nudge_Score"]
    .round(3)
)

gold_opportunity["Avg_Balance"] = (
    gold_opportunity["Avg_Balance"]
    .round(2)
)

gold_opportunity = (
    gold_opportunity
    .sort_values(
        "Customers",
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("GOLD OPPORTUNITY BY PERSONA")
print("=" * 70)

display(gold_opportunity)

======================================================================
GOLD OPPORTUNITY BY PERSONA
======================================================================

,Persona,Customers,High_Priority,Medium_Priority,Low_Priority,Avg_Nudge_Score,Avg_Balance,Customer_%
0,Inactive Investor,2378,0,2378,0,0.241,1366.10,21.30
1,Balanced Investor,2151,0,2151,0,0.419,1636.40,19.27
2,General Investor,1873,0,1873,0,0.399,930.03,16.78
3,Low Engagement User,1455,0,0,1455,0.175,138.96,13.04
4,Emerging Investor,1168,0,1168,0,0.327,236.58,10.46
5,Potential Investor,926,0,926,0,0.341,391.79,8.30
6,Dormant Wealth Holder,555,555,0,0,0.334,6143.91,4.97
7,Growth Investor,433,433,0,0,0.582,6473.70,3.88
8,Premium Investor,223,223,0,0,0.599,6712.32,2.00

In [25]:
# ============================================================
# CELL 23 — GOLD NUDGE CHANNEL ANALYSIS
# ============================================================

gold_channel_summary = (
    final_gold_nudgeiq
    .groupby("Gold_Channel")
    .agg(
        Customers=("Customer_ID", "count"),
        High_Priority=(
            "Gold_Nudge_Priority",
            lambda x: (x == "HIGH").sum()
        ),
        Medium_Priority=(
            "Gold_Nudge_Priority",
            lambda x: (x == "MEDIUM").sum()
        ),
        Low_Priority=(
            "Gold_Nudge_Priority",
            lambda x: (x == "LOW").sum()
        )
    )
    .reset_index()
)

gold_channel_summary["Percentage"] = (
    gold_channel_summary["Customers"]
    / len(final_gold_nudgeiq)
    * 100
).round(2)

gold_channel_summary = (
    gold_channel_summary
    .sort_values(
        "Customers",
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("GOLD NUDGE CHANNEL ALLOCATION")
print("=" * 70)

display(gold_channel_summary)

======================================================================
GOLD NUDGE CHANNEL ALLOCATION
======================================================================

,Gold_Channel,Customers,High_Priority,Medium_Priority,Low_Priority,Percentage
0,Digital,7573,0,6118,1455,67.85
1,Digital + RM,2378,0,2378,0,21.30
2,Relationship Manager,778,778,0,0,6.97
3,RM + Digital,433,433,0,0,3.88

In [26]:
# ============================================================
# CELL 24 — FINANCIAL OPPORTUNITY BY PERSONA
# ============================================================

financial_opportunity = (
    final_gold_nudgeiq
    .groupby("Persona")
    .agg(
        Customers=("Customer_ID", "count"),
        Total_Balance=("balance", "sum"),
        Average_Balance=("balance", "mean"),
        High_Priority_Customers=(
            "Gold_Nudge_Priority",
            lambda x: (x == "HIGH").sum()
        )
    )
    .reset_index()
)

# Percentage of total customer balance
total_balance = (
    final_gold_nudgeiq["balance"].sum()
)

financial_opportunity["Balance_%"] = (
    financial_opportunity["Total_Balance"]
    / total_balance
    * 100
).round(2)

financial_opportunity["Average_Balance"] = (
    financial_opportunity["Average_Balance"]
    .round(2)
)

financial_opportunity["Total_Balance"] = (
    financial_opportunity["Total_Balance"]
    .round(2)
)

financial_opportunity = (
    financial_opportunity
    .sort_values(
        "Total_Balance",
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("FINANCIAL OPPORTUNITY BY PERSONA")
print("=" * 70)

print(
    "\nTotal customer balance:",
    round(total_balance, 2)
)

display(financial_opportunity)

======================================================================
FINANCIAL OPPORTUNITY BY PERSONA
======================================================================

Total customer balance: 17061547

,Persona,Customers,Total_Balance,Average_Balance,High_Priority_Customers,Balance_%
0,Balanced Investor,2151,3519886,1636.40,0,20.63
1,Dormant Wealth Holder,555,3409868,6143.91,555,19.99
2,Inactive Investor,2378,3248593,1366.10,0,19.04
3,Growth Investor,433,2803113,6473.70,433,16.43
4,General Investor,1873,1741939,930.03,0,10.21
5,Premium Investor,223,1496848,6712.32,223,8.77
6,Potential Investor,926,362796,391.79,0,2.13
7,Emerging Investor,1168,276324,236.58,0,1.62
8,Low Engagement User,1455,202180,138.96,0,1.19

In [27]:
# ============================================================
# CELL 25 — GOLD PRIORITY OPPORTUNITY MATRIX
# ============================================================

gold_priority_matrix = (
    final_gold_nudgeiq
    .groupby("Gold_Nudge_Priority")
    .agg(
        Customers=("Customer_ID", "count"),
        Total_Balance=("balance", "sum"),
        Average_Balance=("balance", "mean"),
        Average_Nudge_Score=("Nudge_Priority_Score", "mean")
    )
    .reset_index()
)

# Customer percentage
gold_priority_matrix["Customer_%"] = (
    gold_priority_matrix["Customers"]
    / len(final_gold_nudgeiq)
    * 100
).round(2)

# Balance percentage
gold_priority_matrix["Balance_%"] = (
    gold_priority_matrix["Total_Balance"]
    / final_gold_nudgeiq["balance"].sum()
    * 100
).round(2)

# Formatting
gold_priority_matrix["Total_Balance"] = (
    gold_priority_matrix["Total_Balance"]
    .round(2)
)

gold_priority_matrix["Average_Balance"] = (
    gold_priority_matrix["Average_Balance"]
    .round(2)
)

gold_priority_matrix["Average_Nudge_Score"] = (
    gold_priority_matrix["Average_Nudge_Score"]
    .round(3)
)

# Sort in business priority order
priority_order = {
    "HIGH": 1,
    "MEDIUM": 2,
    "LOW": 3
}

gold_priority_matrix["sort_order"] = (
    gold_priority_matrix["Gold_Nudge_Priority"]
    .map(priority_order)
)

gold_priority_matrix = (
    gold_priority_matrix
    .sort_values("sort_order")
    .drop(columns="sort_order")
    .reset_index(drop=True)
)

print("=" * 70)
print("GOLD PRIORITY OPPORTUNITY MATRIX")
print("=" * 70)

display(gold_priority_matrix)

======================================================================
GOLD PRIORITY OPPORTUNITY MATRIX
======================================================================

,Gold_Nudge_Priority,Customers,Total_Balance,Average_Balance,Average_Nudge_Score,Customer_%,Balance_%
0,HIGH,1211,7709829,6366.50,0.472,10.85,45.19
1,MEDIUM,8496,9149538,1076.92,0.344,76.12,53.63
2,LOW,1455,202180,138.96,0.175,13.04,1.19

In [28]:
# ============================================================
# CELL 26 — GOLD CAMPAIGN RESOURCE STRATEGY
# ============================================================

strategy_map = {
    "HIGH": "High-touch RM / personalized intervention",
    "MEDIUM": "Digital-first personalized campaign",
    "LOW": "Low-cost digital awareness campaign"
}

gold_priority_matrix["Recommended_Strategy"] = (
    gold_priority_matrix["Gold_Nudge_Priority"]
    .map(strategy_map)
)

display(
    gold_priority_matrix[
        [
            "Gold_Nudge_Priority",
            "Customers",
            "Customer_%",
            "Total_Balance",
            "Balance_%",
            "Average_Balance",
            "Average_Nudge_Score",
            "Recommended_Strategy"
        ]
    ]
)

,Gold_Nudge_Priority,Customers,Customer_%,Total_Balance,Balance_%,Average_Balance,Average_Nudge_Score,Recommended_Strategy
0,HIGH,1211,10.85,7709829,45.19,6366.50,0.472,High-touch RM / personalized intervention
1,MEDIUM,8496,76.12,9149538,53.63,1076.92,0.344,Digital-first personalized campaign
2,LOW,1455,13.04,202180,1.19,138.96,0.175,Low-cost digital awareness campaign

In [29]:
# ============================================================
# CELL 27 — GOLD NUDGE CAMPAIGN FUNNEL
# ============================================================

gold_funnel = pd.DataFrame({
    "Stage": [
        "Eligible Customers",
        "Gold Nudge Assigned",
        "Nudge Delivered",
        "Nudge Viewed / Opened",
        "Gold Interest",
        "Gold Enquiry",
        "Gold Application",
        "Gold Purchase",
        "Gold Investment Value",
        "Repeat Gold Purchase"
    ],

    "Definition": [
        "Customers identified by NudgeIQ for a gold strategy",
        "Customers assigned a personalized gold nudge",
        "Customers successfully reached through the assigned channel",
        "Customers who view or open the gold communication",
        "Customers showing measurable interest in gold",
        "Customers initiating a gold-related enquiry",
        "Customers beginning the gold investment process",
        "Customers completing a gold investment",
        "Monetary value of completed gold investments",
        "Customers making a subsequent gold investment"
    ],

    "Current_Data_Available": [
        "YES",
        "YES",
        "NO",
        "NO",
        "NO",
        "NO",
        "NO",
        "NO",
        "NO",
        "NO"
    ],

    "KPI": [
        "Gold Nudge Coverage",
        "Gold Strategy Assignment Rate",
        "Nudge Delivery Rate",
        "Nudge Engagement Rate",
        "Gold Interest Rate",
        "Gold Enquiry Rate",
        "Gold Application Rate",
        "Gold Conversion Rate",
        "Gold Investment Value",
        "Repeat Gold Purchase Rate"
    ]
})

print("=" * 70)
print("GOLD NUDGE CAMPAIGN FUNNEL")
print("=" * 70)

display(gold_funnel)

======================================================================
GOLD NUDGE CAMPAIGN FUNNEL
======================================================================

,Stage,Definition,Current_Data_Available,KPI
0,Eligible Customers,Customers identified by NudgeIQ for a gold str...,YES,Gold Nudge Coverage
1,Gold Nudge Assigned,Customers assigned a personalized gold nudge,YES,Gold Strategy Assignment Rate
2,Nudge Delivered,Customers successfully reached through the ass...,NO,Nudge Delivery Rate
3,Nudge Viewed / Opened,Customers who view or open the gold communication,NO,Nudge Engagement Rate
4,Gold Interest,Customers showing measurable interest in gold,NO,Gold Interest Rate
5,Gold Enquiry,Customers initiating a gold-related enquiry,NO,Gold Enquiry Rate
6,Gold Application,Customers beginning the gold investment process,NO,Gold Application Rate
7,Gold Purchase,Customers completing a gold investment,NO,Gold Conversion Rate
8,Gold Investment Value,Monetary value of completed gold investments,NO,Gold Investment Value
9,Repeat Gold Purchase,Customers making a subsequent gold investment,NO,Repeat Gold Purchase Rate

In [30]:
# ============================================================
# CELL 28 — CURRENT GOLD NUDGE COVERAGE
# ============================================================

coverage_metrics = pd.DataFrame({
    "Metric": [
        "Total Customers",
        "Customers with Gold Strategy",
        "High Priority Customers",
        "Medium Priority Customers",
        "Low Priority Customers",
        "Customers with Gold Action",
        "Customers with Gold Channel",
        "Customers with Gold KPI"
    ],

    "Value": [
        len(final_gold_nudgeiq),

        (
            final_gold_nudgeiq["Gold_Nudge"]
            .eq("YES")
            .sum()
        ),

        (
            final_gold_nudgeiq["Gold_Nudge_Priority"]
            .eq("HIGH")
            .sum()
        ),

        (
            final_gold_nudgeiq["Gold_Nudge_Priority"]
            .eq("MEDIUM")
            .sum()
        ),

        (
            final_gold_nudgeiq["Gold_Nudge_Priority"]
            .eq("LOW")
            .sum()
        ),

        final_gold_nudgeiq["Gold_Nudge_Action"]
        .notna()
        .sum(),

        final_gold_nudgeiq["Gold_Channel"]
        .notna()
        .sum(),

        final_gold_nudgeiq["Gold_KPI"]
        .notna()
        .sum()
    ]
})

print("=" * 70)
print("CURRENT NUDGEIQ GOLD COVERAGE")
print("=" * 70)

display(coverage_metrics)

======================================================================
CURRENT NUDGEIQ GOLD COVERAGE
======================================================================

                         Metric  Value
0               Total Customers  11162
1  Customers with Gold Strategy  11162
2       High Priority Customers   1211
3     Medium Priority Customers   8496
4        Low Priority Customers   1455
5    Customers with Gold Action  11162
6   Customers with Gold Channel  11162
7       Customers with Gold KPI  11162

In [31]:
# ============================================================
# CELL 29 — GOLD OPPORTUNITY QUADRANT
# ============================================================

# ------------------------------------------------------------
# Determine data-driven thresholds
# ------------------------------------------------------------

balance_threshold = (
    final_gold_nudgeiq["balance"]
    .median()
)

priority_threshold = (
    final_gold_nudgeiq["Nudge_Priority_Score"]
    .median()
)

print("=" * 70)
print("GOLD OPPORTUNITY QUADRANT")
print("=" * 70)

print(
    f"\nFinancial capacity threshold (median balance): "
    f"₹{balance_threshold:,.2f}"
)

print(
    f"Behavioral priority threshold (median Nudge Score): "
    f"{priority_threshold:.3f}"
)


# ------------------------------------------------------------
# Assign quadrant
# ------------------------------------------------------------

def assign_gold_quadrant(row):

    high_balance = (
        row["balance"] >= balance_threshold
    )

    high_priority = (
        row["Nudge_Priority_Score"] >= priority_threshold
    )

    if high_balance and high_priority:
        return "STRATEGIC GOLD TARGET"

    elif not high_balance and high_priority:
        return "PRIORITY GOLD TARGET"

    elif high_balance and not high_priority:
        return "NURTURE GOLD OPPORTUNITY"

    else:
        return "GOLD AWARENESS"

    
final_gold_nudgeiq["Gold_Opportunity_Quadrant"] = (
    final_gold_nudgeiq.apply(
        assign_gold_quadrant,
        axis=1
    )
)


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

quadrant_summary = (
    final_gold_nudgeiq
    .groupby("Gold_Opportunity_Quadrant")
    .agg(
        Customers=("Customer_ID", "count"),
        Total_Balance=("balance", "sum"),
        Average_Balance=("balance", "mean"),
        Average_Nudge_Score=(
            "Nudge_Priority_Score",
            "mean"
        )
    )
    .reset_index()
)

quadrant_summary["Customer_%"] = (
    quadrant_summary["Customers"]
    / len(final_gold_nudgeiq)
    * 100
).round(2)

quadrant_summary["Balance_%"] = (
    quadrant_summary["Total_Balance"]
    / final_gold_nudgeiq["balance"].sum()
    * 100
).round(2)

quadrant_summary["Total_Balance"] = (
    quadrant_summary["Total_Balance"]
    .round(2)
)

quadrant_summary["Average_Balance"] = (
    quadrant_summary["Average_Balance"]
    .round(2)
)

quadrant_summary["Average_Nudge_Score"] = (
    quadrant_summary["Average_Nudge_Score"]
    .round(3)
)

display(
    quadrant_summary.sort_values(
        "Total_Balance",
        ascending=False
    )
)

======================================================================
GOLD OPPORTUNITY QUADRANT
======================================================================

Financial capacity threshold (median balance): ₹550.00
Behavioral priority threshold (median Nudge Score): 0.334

,Gold_Opportunity_Quadrant,Customers,Total_Balance,Average_Balance,Average_Nudge_Score,Customer_%,Balance_%
3,STRATEGIC GOLD TARGET,3427,11379039,3320.41,0.438,30.70,66.69
1,NURTURE GOLD OPPORTUNITY,2158,4969112,2302.65,0.263,19.33,29.12
2,PRIORITY GOLD TARGET,2155,389671,180.82,0.393,19.31,2.28
0,GOLD AWARENESS,3422,323725,94.60,0.243,30.66,1.90